version: '3.1'

services:

  db:
    image: mysql:8.2.0
    container_name: mysql-sample
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple-app
      MYSQL_USER: simple-app-user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
